# Generated by Django 4.2.10 on 2026-03-15 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_systemoperationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="vip_level",
            field=models.IntegerField(
                choices=[(0, "非VIP"), (1, "VIP")], default=0, verbose_name="VIP等级"
            ),
        ),
        migrations.AlterField(
            model_name="viporder",
            name="vip_level",
            field=models.IntegerField(
                choices=[(0, "非VIP"), (1, "VIP")], default=1, verbose_name="VIP等级"
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_profile",
                    models.BooleanField(default=True, verbose_name="公开个人资料"),
                ),
                (
                    "show_history",
                    models.BooleanField(default=True, verbose_name="显示观看历史"),
                ),
                (
                    "allow_messages",
                    models.BooleanField(default=True, verbose_name="允许私信"),
                ),
                (
                    "public_collections",
                    models.BooleanField(default=False, verbose_name="公开收藏夹"),
                ),
                (
                    "show_following",
                    models.BooleanField(default=True, verbose_name="显示关注列表"),
                ),
                ("autoplay", models.BooleanField(default=True, verbose_name="自动播放")),
                (
                    "quality",
                    models.CharField(
                        default="auto", max_length=10, verbose_name="默认清晰度"
                    ),
                ),
                (
                    "speed",
                    models.CharField(
                        default="1.0", max_length=5, verbose_name="默认播放速度"
                    ),
                ),
                (
                    "remember_volume",
                    models.BooleanField(default=True, verbose_name="记忆音量"),
                ),
                ("danmaku", models.BooleanField(default=True, verbose_name="弹幕显示")),
                (
                    "remember_progress",
                    models.BooleanField(default=True, verbose_name="记忆播放进度"),
                ),
                ("dark_mode", models.BooleanField(default=False, verbose_name="深色模式")),
                (
                    "layout",
                    models.CharField(
                        default="grid", max_length=10, verbose_name="首页布局"
                    ),
                ),
                ("page_size", models.IntegerField(default=24, verbose_name="每页显示数量")),
                (
                    "hover_preview",
                    models.BooleanField(default=True, verbose_name="悬停预览"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "用户设置", "verbose_name_plural": "用户设置",},
        ),
        migrations.CreateModel(
            name="LoginDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=100, verbose_name="设备名称")),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=20, verbose_name="设备类型"),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="浏览器"),
                ),
                (
                    "os",
                    models.CharField(blank=True, max_length=50, verbose_name="操作系统"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="位置"),
                ),
                (
                    "last_active",
                    models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="当前设备")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="首次登录时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "登录设备",
                "verbose_name_plural": "登录设备",
                "ordering": ["-last_active"],
            },
        ),
    ]
