"""
Django settings for video project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8767!m4@bj3oq$jl2qov58iitt_6lk+z&9*-2^lvb+95@-tub8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    "daphne",  # Channels ASGI 服务器，需要放在最前面
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",  
    "corsheaders",
    "drf_yasg",
    "django_filters",
    "channels",  

    "users",
    "videos",
    "core",
    "authentication",
    "ai_service",
    "captcha",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.logging_middleware.OperationLogMiddleware",
]

ROOT_URLCONF = "video.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "video.wsgi.application"
ASGI_APPLICATION = "video.asgi.application"

# Channels 配置（使用 Redis 作为 Channel Layer）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379, 2)],  # 使用 DB 2，与 Celery 分开
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "video_platform",
        "USER": "root",
        "PASSWORD": "123456",  
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),  
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),  # 前端使用Bearer前缀
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
    
    # 添加额外的设置
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',
}


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
}


CORS_ALLOW_ALL_ORIGINS = True  
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'range', 
]
CORS_EXPOSE_HEADERS = [
    'content-range',
    'content-length',
    'accept-ranges',
]


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # 消除 Celery 6.0 警告

# 任务结果过期时间（秒）
CELERY_RESULT_EXPIRES = 3600 

# Celery Worker 内存管理配置
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10  # 每个 worker 处理 10 个任务后重启，防止内存泄漏
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 500000  # 单个 worker 最大内存 500MB（单位：KB）

# Celery 日志配置
CELERY_WORKER_HIJACK_ROOT_LOGGER = False  # 不劫持根日志器，使用 Django 的日志配置
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

# Django Cache 配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://localhost:6379/1', 
        'KEY_PREFIX': 'video_web',
        'TIMEOUT': 3600,  # 默认缓存超时时间（秒）
    }
}

# Captcha 配置（提升清晰度）
CAPTCHA_IMAGE_SIZE = (160, 60)
CAPTCHA_FONT_SIZE = 36
CAPTCHA_LENGTH = 4
CAPTCHA_TIMEOUT = 5

# 视频存储设置
VIDEO_UPLOAD_PATH = os.path.join(MEDIA_ROOT, 'videos/uploads')
VIDEO_PROCESSED_PATH = os.path.join(MEDIA_ROOT, 'videos/processed')
VIDEO_THUMBNAIL_PATH = os.path.join(MEDIA_ROOT, 'videos/thumbnails')

# 邮件设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # 163邮箱SMTP服务器
EMAIL_PORT = 465  # 163邮箱SMTP SSL端口
EMAIL_USE_SSL = True 
EMAIL_HOST_USER = 'zzy1511995259@163.com' 
EMAIL_HOST_PASSWORD = 'CRhufbUSnGKujcC8' 
DEFAULT_FROM_EMAIL = 'zzy1511995259@163.com' 
SITE_NAME = '视频网站'  

# 邮件调试设置
EMAIL_TIMEOUT = 30  # 设置超时时间为30秒
EMAIL_USE_LOCALTIME = True  # 使用本地时间

# 日志目录
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'celery': {
            'format': '[{asctime}] [{levelname}] [{name}] {message}',
            'style': '{',
        },
        'subtitle': {
            'format': '{asctime} [{levelname}] [{funcName}:{lineno}] - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Django 主日志
        'django_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Celery 任务日志
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'celery.log'),
            'formatter': 'celery',
            'encoding': 'utf-8',
        },
        # 字幕检测日志
        'subtitle_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'subtitle_detection.log'),
            'formatter': 'subtitle',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        '': {  # 根日志器
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.email': {
            'handlers': ['console', 'django_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Celery 相关日志
        'celery': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.worker': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.beat': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 视频任务日志
        'videos.tasks': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 字幕检测日志
        'videos.subtitle_detector': {
            'handlers': ['console', 'subtitle_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # AI 服务日志（暂时输出到 django.log）
        'ai_service': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_service.tasks': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_service.services': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# DeepSeek API 
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '') 
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
DEEPSEEK_MODEL = os.environ.get('DEEPSEEK_MODEL', 'deepseek-chat')


# NSFW 检测模型配置
NSFW_MODEL_PATH = os.path.join(BASE_DIR, 'video', 'models', 'EVA-based_Fast_NSFW_Image_Classifier')
NSFW_DEFAULT_THRESHOLD_LEVEL = 'medium'  # low/medium/high
NSFW_DEFAULT_THRESHOLD = 0.6  # 0.0-1.0
NSFW_DEFAULT_FPS = 1  # 每秒抽帧数
NSFW_BATCH_SIZE = 4  # 批处理大小

# 支付宝沙箱配置
ALIPAY_APPID = '9021000161677112'  # 替换为你的沙箱AppID
ALIPAY_APP_PRIVATE_KEY = '''
MIIEpAIBAAKCAQEAvCCrXQI0+udA/NjI5/RDSx2R+l4A830wLewxljD4gEvjJ144e1oWCBI7+HiZmAWNqVYYgkpjLYmHynmQmK4vBNjkoo22/ydtXK9iN9zGfz9C7Ut3BVb1E8DHnDZ9tOP4hGoDOZyMab1eBpcoqQ5tkpKPLa2UMPMxWAQXA9upuNKjn6GmsdEKNb5PqCRXeZWzunEXKlMv3++j4ulkn/d8EbY7ZPOUFgJmNqdxITn3Z1dRCiXbQUNQcbTU1dyDXTIR7p71SyIzhNFb4Vv6fKqoOyQ35bzm8j1D0hq9Lk4q+OU/wYc7IB7xKKjHLRmFkcZMRz9edsh39PyOjxfXPkD/pwIDAQABAoIBAGEEI/sp+TJu8ZezICBmWhGxpSdNNQZcR+1WwdenV2+qMvGJaG1MbtIovR6M6wB31K9ABBGk1PKV2x4yhLwID51bUMT3eiipJ3/Fvkv6oa7ba+M9qJprVqWiJA5OF5OigPWgSht6vPqGuqeBammMVDtjM00mF6cKsyalrUzDCgqSSuLNu1+5bme0sC7+EB4MlUQVpsTI0CMuQ2gxKyek9RHFxY3bagPKps7JbvwHCJYKX8dcKm6NhNluFgLREAxVmBMpEidubEKEwzgHqLyi+/fI4F001gOiIvXsgl+1OBEPQtJ4En7MMjmMoxDOxZQ46Jv9JsQj7Ex0uXGvJFHpktkCgYEA7R0gdXd3Qcau4Xnop49dG1hYhCF3mLpv4+EoEuqN5S3+C0NdMm/B4vIz30IvVa3L6g6CI8vEKyC+ZHFpF5g9gOSpeGc0qT4rs3gzH21HOikua8GAokJfT4+DPhZti4/5PugrxXhl0uaOUkrUSYEAvI9Ai+vLeW1e/r8nIMWjphMCgYEAyxywdOlTiGtmqSbM8fUT6p2vsIET+BJTF9TRa5PTXxL2tOMYz2GyTU9Xia35D77uLzpjYwbRAme3pFcJHpqAkMKwJbHknptS5EwkX4+dLKZXREhAVY9JkAB0PelwvzyCYiuHGOt898QOC28ZbXWzN4crzW924cnolOwLmksIAp0CgYEAydlXvme6v+XRDeTnp2ylyBeHEsQiuYNMqOMNaD0AGi7y6sen2L3GgdnJSq9e+EMBKfi71JksH8K6EWtyGUHiaY0+r168N67TKO6UJpayYdKYz+ZkCL0TwfjbsskI7BveBC1Exc/ebpESav+EhCYraFlSi0ppZq8yhQ5Y0s8spr0CgYEAxbnFEdr+haRASVTLWJQDcndVTBcsEGgOWfnEcNx0fW5hmpAlW+U4hUhC6HXjKu/swS8vB3zgRV4giSxtZUx08feFMPzvmXONi0+QbTLKiGfaNk+7yU73BudaQdcZ+iD2sIi9OIYunqhOH9VkxIk7EUhWXOQwr/c1opvzY529S4UCgYA2UokixckuFlZZZVy+5K98C0FBcfq9khTmzAp7kKw9f5+YrZXi1UW2llTrRXu2yfNBhT5VxyBU7EXxF0zFUJWJckgOXsbmsa9Popxkctpq/YIkWdjWPU+2tQczV3e12ieIZ2e8rjy4TNd4IclkAepEJpmaPvMlV2MP013bCEd+UQ==
'''  
ALIPAY_PUBLIC_KEY = '''
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1xZGsoHWUu6HLqyt19so3UvMQlO6cUvrcLNK//jB+lf3MDALKE3uVyfR69sob6xJEa3FCA+irz+2e74UIO+LwJlxe4jKWtXYMuHPbyJJzzareoyM4Gh7axrdAqY157F2OvMcb0gXEIMPJ++zPJn/WaSgagNguZr38HUV9RrpDk9bNgEKnUVVn8o3s9BYr3WRK/vBaC3vy2abgoOg/bIGj66TOMSfe1bpyo+si6WLz9g8OP+yI4XmVioF9Hj1scvNSBNOERuP+3FbyZOeaJ2GRUaqEnYwV7aXWa7ICX08fUMmByYAZvncZ/qinib8qNPiq/w88sPQuknezVT05ixzlQIDAQAB
'''  

ALIPAY_DEBUG = True  # 沙箱模式
ALIPAY_GATEWAY = 'https://mapi.alipaydev.com/gateway.do'  # 沙箱网关

# 支付回调地址（需要根据实际域名修改）
ALIPAY_RETURN_URL = 'http://localhost:5173/user/vip/return'
ALIPAY_NOTIFY_URL = 'http://localhost:8000/api/users/vip/notify/'

# VIP 价格配置
VIP_PRICES = {
    1: {'name': 'VIP会员', 'monthly': 19.9, 'quarterly': 49.9, 'yearly': 149.9},
}

try:
    from .settings_local import *
except ImportError:
    pass
