"""
Django settings for video project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from urllib.parse import urlsplit, urlunsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local development settings from the ignored project-root .env file.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR.parent.parent / '.env')
except ImportError:
    pass


def _env_int(name, default):
    """读取整数配置，并在配置错误时快速失败。"""
    value = os.environ.get(name, str(default))
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f'{name} 必须是整数') from exc


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-only-insecure-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    "daphne",  # Channels ASGI 服务器，需要放在最前面
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",  
    "corsheaders",
    "drf_yasg",
    "django_filters",
    "channels",  

    "users",
    "videos",
    "core",
    "authentication",
    "ai_service",
    "captcha",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.request_id_middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.logging_middleware.OperationLogMiddleware",
    "core.errors.APIErrorResponseMiddleware",
]

ROOT_URLCONF = "video.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "video.wsgi.application"
ASGI_APPLICATION = "video.asgi.application"

# Channels 配置（使用 Redis 作为 Channel Layer）
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')


def _redis_url_for_db(url, db):
    parsed = urlsplit(url)
    return urlunsplit((parsed.scheme, parsed.netloc, f'/{db}', parsed.query, parsed.fragment))


REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', _redis_url_for_db(REDIS_URL, 1))
REDIS_CHANNEL_URL = os.environ.get('REDIS_CHANNEL_URL', _redis_url_for_db(REDIS_URL, 2))


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379, 2)],  # 使用 DB 2，与 Celery 分开
        },
    },
}


CHANNEL_LAYERS["default"]["CONFIG"]["hosts"] = [REDIS_CHANNEL_URL]


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DATABASE", "video_platform"),
        "USER": os.environ.get("MYSQL_USER", "root"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
        "HOST": os.environ.get("MYSQL_HOST", "localhost"),
        "PORT": os.environ.get("MYSQL_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "connect_timeout": _env_int('MYSQL_CONNECT_TIMEOUT', 5),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'EXCEPTION_HANDLER': 'core.errors.api_exception_handler',
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),  
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),  # 前端使用Bearer前缀
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
    
    # 添加额外的设置
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',
}


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
}


CORS_ALLOW_ALL_ORIGINS = True  
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'range', 
]
CORS_EXPOSE_HEADERS = [
    'content-range',
    'content-length',
    'accept-ranges',
]


CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_TASK_DEFAULT_QUEUE = os.environ.get('CELERY_TASK_DEFAULT_QUEUE', 'video_dev')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # 消除 Celery 6.0 警告
CELERY_TASK_TRACK_STARTED = True

# Long-running tasks must not remain invisible forever. Late acknowledgements
# allow a worker crash to return the message to the broker; the hard limit is a
# final safety net after the soft limit has had a chance to clean up.
CELERY_TASK_ANNOTATIONS = {
    'videos.tasks.process_video': {
        'soft_time_limit': _env_int('VIDEO_PROCESS_SOFT_TIME_LIMIT', 7200),
        'time_limit': _env_int('VIDEO_PROCESS_TIME_LIMIT', 7500),
        'acks_late': True,
        'reject_on_worker_lost': True,
    },
    'ai_service.tasks.generate_video_subtitles': {
        'soft_time_limit': _env_int('VIDEO_SUBTITLE_SOFT_TIME_LIMIT', 1800),
        'time_limit': _env_int('VIDEO_SUBTITLE_TIME_LIMIT', 2100),
        'acks_late': True,
        'reject_on_worker_lost': True,
    },
    'ai_service.tasks.detect_video_subtitle': {
        'soft_time_limit': _env_int('VIDEO_SUBTITLE_DETECT_SOFT_TIME_LIMIT', 1800),
        'time_limit': _env_int('VIDEO_SUBTITLE_DETECT_TIME_LIMIT', 2100),
        'acks_late': True,
        'reject_on_worker_lost': True,
    },
    'ai_service.tasks.moderate_video_task': {
        'soft_time_limit': _env_int('VIDEO_MODERATION_SOFT_TIME_LIMIT', 3600),
        'time_limit': _env_int('VIDEO_MODERATION_TIME_LIMIT', 3900),
        'acks_late': True,
        'reject_on_worker_lost': True,
    },
}

# 任务结果过期时间（秒）
CELERY_RESULT_EXPIRES = 3600 

# Celery Worker 内存管理配置
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10  # 每个 worker 处理 10 个任务后重启，防止内存泄漏
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 500000  # 单个 worker 最大内存 500MB（单位：KB）

# Celery 日志配置
CELERY_WORKER_HIJACK_ROOT_LOGGER = False  # 不劫持根日志器，使用 Django 的日志配置
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

# Django Cache 配置
# redis-py 5.x 的 Connection 只接受小写 socket_connect_timeout / socket_timeout
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_CACHE_URL,
        'KEY_PREFIX': 'video_web',
        'OPTIONS': {
            'socket_connect_timeout': _env_int('REDIS_SOCKET_CONNECT_TIMEOUT', 5),
            'socket_timeout': _env_int('REDIS_SOCKET_TIMEOUT', 5),
        },
        'TIMEOUT': 3600,  # 默认缓存超时时间（秒）
    }
}

# Captcha 配置（提升清晰度）
CAPTCHA_IMAGE_SIZE = (160, 60)
CAPTCHA_FONT_SIZE = 36
CAPTCHA_LENGTH = 4
CAPTCHA_TIMEOUT = 5

# 视频存储设置
VIDEO_UPLOAD_PATH = os.path.join(MEDIA_ROOT, 'videos/uploads')
VIDEO_PROCESSED_PATH = os.path.join(MEDIA_ROOT, 'videos/processed')
VIDEO_THUMBNAIL_PATH = os.path.join(MEDIA_ROOT, 'videos/thumbnails')

# 邮件设置
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')
SITE_NAME = os.environ.get('SITE_NAME', 'Video Platform')

# 邮件调试设置
EMAIL_TIMEOUT = 30  # 设置超时时间为30秒
EMAIL_USE_LOCALTIME = True  # 使用本地时间

# 日志目录
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'celery': {
            'format': '[{asctime}] [{levelname}] [{name}] {message}',
            'style': '{',
        },
        'subtitle': {
            'format': '{asctime} [{levelname}] [{funcName}:{lineno}] - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Django 主日志
        'django_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Celery 任务日志
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'celery.log'),
            'formatter': 'celery',
            'encoding': 'utf-8',
        },
        # 字幕检测日志
        'subtitle_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'subtitle_detection.log'),
            'formatter': 'subtitle',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        '': {  # 根日志器
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.email': {
            'handlers': ['console', 'django_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Celery 相关日志
        'celery': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.worker': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.beat': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.task_lifecycle': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 视频任务日志
        'videos.tasks': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 字幕检测日志
        'videos.subtitle_detector': {
            'handlers': ['console', 'subtitle_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # AI 服务日志（暂时输出到 django.log）
        'ai_service': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_service.tasks': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_service.services': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # httpx logs the full request URL at INFO. Alibaba result URLs are
        # short-lived signed URLs, so keep them out of application logs.
        'httpx': {
            'handlers': ['console', 'django_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpcore': {
            'handlers': ['console', 'django_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# AI Provider selection. Missing cloud credentials must not block Django startup.
AI_TEXT_PROVIDER = os.environ.get('AI_TEXT_PROVIDER', 'deepseek')
AI_ASR_PROVIDER = os.environ.get('AI_ASR_PROVIDER', 'disabled')
AI_OCR_PROVIDER = os.environ.get('AI_OCR_PROVIDER', 'disabled')
AI_MODERATION_PROVIDER = os.environ.get('AI_MODERATION_PROVIDER', 'disabled')
AI_STORAGE_PROVIDER = os.environ.get('AI_STORAGE_PROVIDER', 'local')
AI_PROVIDER_TIMEOUT_SECONDS = _env_int('AI_PROVIDER_TIMEOUT_SECONDS', 60)
AI_PROVIDER_MAX_RETRIES = _env_int('AI_PROVIDER_MAX_RETRIES', 2)
AI_TEXT_MAX_INPUT_CHARS = _env_int('AI_TEXT_MAX_INPUT_CHARS', 50000)
AI_CLOUD_MAX_INPUT_BYTES = _env_int('AI_CLOUD_MAX_INPUT_BYTES', 2 * 1024 * 1024 * 1024)
AI_OCR_SAMPLE_COUNT = _env_int('AI_OCR_SAMPLE_COUNT', 8)

# DeepSeek API
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '') 
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
DEEPSEEK_MODEL = os.environ.get('DEEPSEEK_MODEL', 'deepseek-v4-flash')

# Alibaba Cloud AI APIs. Access keys are read only when a provider is invoked.
ALIBABA_CLOUD_ACCESS_KEY_ID = os.environ.get('ALIBABA_CLOUD_ACCESS_KEY_ID', '')
ALIBABA_CLOUD_ACCESS_KEY_SECRET = os.environ.get('ALIBABA_CLOUD_ACCESS_KEY_SECRET', '')
ALIBABA_CLOUD_SECURITY_TOKEN = os.environ.get('ALIBABA_CLOUD_SECURITY_TOKEN', '')
DASHSCOPE_API_KEY = os.environ.get('DASHSCOPE_API_KEY', '')
DASHSCOPE_REGION = os.environ.get('DASHSCOPE_REGION', 'beijing')
DASHSCOPE_BASE_URL = os.environ.get('DASHSCOPE_BASE_URL', '')
DASHSCOPE_ASR_MODEL = os.environ.get('DASHSCOPE_ASR_MODEL', 'fun-asr')
DASHSCOPE_POLL_INTERVAL_SECONDS = _env_int('DASHSCOPE_POLL_INTERVAL_SECONDS', 10)
DASHSCOPE_POLL_TIMEOUT_SECONDS = _env_int('DASHSCOPE_POLL_TIMEOUT_SECONDS', 1500)
AI_AUDIO_EXTRACT_TIMEOUT_SECONDS = _env_int('AI_AUDIO_EXTRACT_TIMEOUT_SECONDS', 900)
ALIYUN_OSS_ENDPOINT = os.environ.get('ALIYUN_OSS_ENDPOINT', 'oss-cn-beijing.aliyuncs.com')
ALIYUN_OSS_BUCKET = os.environ.get('ALIYUN_OSS_BUCKET', '')
ALIYUN_OSS_PREFIX = os.environ.get('ALIYUN_OSS_PREFIX', 'ai-temp/')
ALIYUN_OSS_SIGNED_URL_TTL_SECONDS = _env_int('ALIYUN_OSS_SIGNED_URL_TTL_SECONDS', 21600)
ALIYUN_OSS_TEMP_RETENTION_HOURS = _env_int('ALIYUN_OSS_TEMP_RETENTION_HOURS', 24)
ALIYUN_OCR_ENDPOINT = os.environ.get('ALIYUN_OCR_ENDPOINT', 'ocr-api.cn-hangzhou.aliyuncs.com')
ALIYUN_OCR_MAX_IMAGE_BYTES = _env_int('ALIYUN_OCR_MAX_IMAGE_BYTES', 10 * 1024 * 1024)
ALIYUN_GREEN_REGION = os.environ.get('ALIYUN_GREEN_REGION', 'cn-shanghai')
ALIYUN_GREEN_ENDPOINT = os.environ.get('ALIYUN_GREEN_ENDPOINT', 'green-cip.cn-shanghai.aliyuncs.com')
ALIYUN_VIDEO_MODERATION_SERVICE = os.environ.get('ALIYUN_VIDEO_MODERATION_SERVICE', 'videoDetection')
ALIYUN_MODERATION_POLL_INTERVAL_SECONDS = _env_int('ALIYUN_MODERATION_POLL_INTERVAL_SECONDS', 15)
ALIYUN_MODERATION_POLL_TIMEOUT_SECONDS = _env_int('ALIYUN_MODERATION_POLL_TIMEOUT_SECONDS', 1800)


# NSFW 检测模型配置
NSFW_MODEL_PATH = os.path.join(BASE_DIR, 'video', 'models', 'EVA-based_Fast_NSFW_Image_Classifier')
NSFW_DEFAULT_THRESHOLD_LEVEL = 'medium'  # low/medium/high
NSFW_DEFAULT_THRESHOLD = 0.6  # 0.0-1.0
NSFW_DEFAULT_FPS = 1  # 每秒抽帧数
NSFW_BATCH_SIZE = 4  # 批处理大小

# 支付宝沙箱配置
ALIPAY_APPID = os.environ.get('ALIPAY_APPID', '')
ALIPAY_APP_PRIVATE_KEY = os.environ.get('ALIPAY_APP_PRIVATE_KEY', '').replace('\\n', '\n')
ALIPAY_PUBLIC_KEY = os.environ.get('ALIPAY_PUBLIC_KEY', '').replace('\\n', '\n')
ALIPAY_DEBUG = os.environ.get('ALIPAY_DEBUG', 'true').lower() == 'true'
ALIPAY_GATEWAY = os.environ.get('ALIPAY_GATEWAY', 'https://openapi-sandbox.dl.alipaydev.com/gateway.do')

# 支付回调地址（需要根据实际域名修改）
ALIPAY_RETURN_URL = os.environ.get('ALIPAY_RETURN_URL', 'http://localhost:5173/user/vip/return')
ALIPAY_NOTIFY_URL = os.environ.get('ALIPAY_NOTIFY_URL', 'http://localhost:8000/api/users/vip/notify/')
# VIP 价格配置
VIP_PRICES = {
    1: {'name': 'VIP会员', 'monthly': 19.9, 'quarterly': 49.9, 'yearly': 149.9},
}

try:
    from .settings_local import *
except ImportError:
    pass
